# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Test.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_myMainWindow(object):
    def setupUi(self, myMainWindow):
        myMainWindow.setObjectName("myMainWindow")
        myMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(myMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 490, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 490, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 490, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.myTableView = QtWidgets.QTableView(self.centralwidget)
        self.myTableView.setGeometry(QtCore.QRect(90, 110, 471, 221))
        self.myTableView.setObjectName("myTableView")
        self.qryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.qryBtn.setGeometry(QtCore.QRect(80, 30, 75, 23))
        self.qryBtn.setObjectName("qryBtn")
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.addBtn.setObjectName("addBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(290, 30, 75, 23))
        self.delBtn.setObjectName("delBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 380, 54, 12))
        self.label.setObjectName("label")
        self.del2Btn = QtWidgets.QPushButton(self.centralwidget)
        self.del2Btn.setGeometry(QtCore.QRect(380, 30, 75, 23))
        self.del2Btn.setObjectName("del2Btn")
        myMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(myMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        myMainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(myMainWindow)
        self.statusBar.setObjectName("statusBar")
        myMainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(myMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(myMainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOpen = QtWidgets.QAction(myMainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(myMainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(myMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChange_title = QtWidgets.QAction(myMainWindow)
        self.actionChange_title.setObjectName("actionChange_title")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionChange_title)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(myMainWindow)
        self.pushButton.clicked.connect(myMainWindow.close)
        self.pushButton_2.clicked.connect(myMainWindow.allBtnHide)
        self.pushButton_3.clicked.connect(myMainWindow.allBtnHide)
        QtCore.QMetaObject.connectSlotsByName(myMainWindow)

    def retranslateUi(self, myMainWindow):
        _translate = QtCore.QCoreApplication.translate
        myMainWindow.setWindowTitle(_translate("myMainWindow", "MainWindow"))
        self.pushButton.setText(_translate("myMainWindow", "点我关闭"))
        self.pushButton_2.setText(_translate("myMainWindow", "点我消失"))
        self.pushButton_3.setText(_translate("myMainWindow", "点我全没"))
        self.qryBtn.setText(_translate("myMainWindow", "查询"))
        self.addBtn.setToolTip(_translate("myMainWindow", "插入一条记录"))
        self.addBtn.setText(_translate("myMainWindow", "增加"))
        self.delBtn.setToolTip(_translate("myMainWindow", "<html><head/><body><p>删除一条记录</p></body></html>"))
        self.delBtn.setText(_translate("myMainWindow", "删除"))
        self.label.setText(_translate("myMainWindow", "我是中文"))
        self.del2Btn.setText(_translate("myMainWindow", "删除2"))
        self.menuFile.setTitle(_translate("myMainWindow", "File"))
        self.menuEdit.setTitle(_translate("myMainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("myMainWindow", "Help"))
        self.actionAbout.setText(_translate("myMainWindow", "About"))
        self.actionAbout.setToolTip(_translate("myMainWindow", "About?????"))
        self.actionHelp.setText(_translate("myMainWindow", "Help"))
        self.actionOpen.setText(_translate("myMainWindow", "Open"))
        self.actionSave_As.setText(_translate("myMainWindow", "Save As"))
        self.actionExit.setText(_translate("myMainWindow", "退了？"))
        self.actionExit.setToolTip(_translate("myMainWindow", "<html><head/><body><p>real exit?</p></body></html>"))
        self.actionChange_title.setText(_translate("myMainWindow", "change title"))

